# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Confirmation(object):
    def setupUi(self, Confirmation):
        Confirmation.setObjectName("Confirmation")
        Confirmation.resize(320, 251)
        Confirmation.setStyleSheet("background-image: url(:/images/img/confirm.png);")
        self.frame_2 = QtWidgets.QFrame(Confirmation)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 320, 41))
        self.frame_2.setMinimumSize(QtCore.QSize(320, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(320, 16777215))
        self.frame_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame_2.setStyleSheet("QFrame{\n"
"background:rgba(0,0,0,0.80);\n"
"}\n"
"QFrame{\n"
"\n"
"border-radius:none;\n"
"\n"
"}\n"
"\n"
"QFrame:hover{\n"
"background:rgba(0,0,0,0.9);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"color:white;\n"
"background:transparent;")
        self.label_2.setObjectName("label_2")
        self.btn_close = QtWidgets.QPushButton(self.frame_2)
        self.btn_close.setGeometry(QtCore.QRect(279, 0, 41, 38))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_close.setFont(font)
        self.btn_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_close.setStyleSheet("QPushButton{\n"
"background:rgba(0, 0, 0,0.01);\n"
"color:silver;\n"
"\n"
"border-radius:none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background:red;\n"
"color:white\n"
"}")
        self.btn_close.setObjectName("btn_close")
        self.frame = QtWidgets.QFrame(Confirmation)
        self.frame.setGeometry(QtCore.QRect(0, 40, 321, 161))
        self.frame.setStyleSheet("QFrame{\n"
"    background: rgba(0,0,0,0.7);\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background: rgba(0,0,0,0.8);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(70, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("\n"
"color:white;\n"
"background:transparent;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(30, 30, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("\n"
"color:white;\n"
"background:transparent;")
        self.label_7.setObjectName("label_7")
        self.txt_confirm = QtWidgets.QPlainTextEdit(self.frame)
        self.txt_confirm.setEnabled(False)
        self.txt_confirm.setGeometry(QtCore.QRect(22, 70, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_confirm.setFont(font)
        self.txt_confirm.setStyleSheet("QPlainTextEdit{\n"
"background:transparent;\n"
"border:none;\n"
"color:white;}\n"
"\n"
"QPlainTextEdit:hover{\n"
"color:white;\n"
"}")
        self.txt_confirm.setObjectName("txt_confirm")
        self.frame_3 = QtWidgets.QFrame(Confirmation)
        self.frame_3.setGeometry(QtCore.QRect(0, 200, 321, 51))
        self.frame_3.setStyleSheet("QFrame{\n"
"background:rgba(0,0,0,0.7);\n"
"}\n"
"QFrame{\n"
"\n"
"border-radius:none;\n"
"\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btn_ok = QtWidgets.QPushButton(self.frame_3)
        self.btn_ok.setGeometry(QtCore.QRect(207, 12, 101, 31))
        self.btn_ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ok.setStyleSheet("\n"
"QPushButton{\n"
"background:rgb(83, 152, 255);\n"
"border-radius:3px;\n"
"color:rgb(240, 240, 240);\n"
"font-size:14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:rgb(68, 117, 222);\n"
"color:white;\n"
"font-size:14.5px;\n"
" }\n"
"")
        self.btn_ok.setObjectName("btn_ok")
        self.btn_cancel = QtWidgets.QPushButton(self.frame_3)
        self.btn_cancel.setGeometry(QtCore.QRect(100, 12, 101, 31))
        self.btn_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancel.setStyleSheet("\n"
"QPushButton{\n"
"background:rgb(83, 152, 255);\n"
"border-radius:3px;\n"
"color:rgb(240, 240, 240);\n"
"font-size:14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:rgb(68, 117, 222);\n"
"color:white;\n"
"font-size:14.5px;\n"
" }\n"
"")
        self.btn_cancel.setObjectName("btn_cancel")

        self.retranslateUi(Confirmation)
        QtCore.QMetaObject.connectSlotsByName(Confirmation)

    def retranslateUi(self, Confirmation):
        _translate = QtCore.QCoreApplication.translate
        Confirmation.setWindowTitle(_translate("Confirmation", "Confirmation"))
        self.label_2.setText(_translate("Confirmation", "Tasdiqlash"))
        self.btn_close.setText(_translate("Confirmation", "✕"))
        self.label_6.setText(_translate("Confirmation", "Tasdiqlash"))
        self.label_7.setText(_translate("Confirmation", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">✔️</span></p></body></html>"))
        self.txt_confirm.setPlainText(_translate("Confirmation", "Chiqishni hohlaysizmi?"))
        self.btn_ok.setText(_translate("Confirmation", "OK"))
        self.btn_cancel.setText(_translate("Confirmation", "Cancel"))
import images_rc
