# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(450, 500)
        Login.setMinimumSize(QtCore.QSize(450, 500))
        Login.setMaximumSize(QtCore.QSize(450, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/img/icon/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Login.setWindowIcon(icon)
        Login.setStyleSheet("QFrame{\n"
"    background:rgba(0,0,0,0.4);\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background:rgba(0,0,0,0.6);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    font-size:25px;;\n"
"    color:white;\n"
"    border:none;\n"
"    background:transparent;\n"
"    border-bottom:1px solid white;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background:rgba(0,0,0,0.04);\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    background:rgb(83, 152, 255);\n"
"    border-radius:10px;\n"
"    color:#fff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:none;\n"
"    background:rgb(68, 117, 222)\n"
"}\n"
"\n"
"QCheckBox{\n"
"    color:silver;\n"
"    background:transparent\n"
"}\n"
"QCheckBox:hover{\n"
"    color:white;\n"
"}")
        self.frame = QtWidgets.QFrame(Login)
        self.frame.setGeometry(QtCore.QRect(10, 70, 431, 411))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.baslik_2 = QtWidgets.QLabel(self.frame)
        self.baslik_2.setGeometry(QtCore.QRect(10, 20, 411, 41))
        self.baslik_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.baslik_2.setStyleSheet("font-size:40px;\n"
"color:white;\n"
"background:transparent;\n"
"text-align: center;")
        self.baslik_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.baslik_2.setTextFormat(QtCore.Qt.AutoText)
        self.baslik_2.setScaledContents(False)
        self.baslik_2.setAlignment(QtCore.Qt.AlignCenter)
        self.baslik_2.setOpenExternalLinks(True)
        self.baslik_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.baslik_2.setObjectName("baslik_2")
        self.baslik = QtWidgets.QLabel(self.frame)
        self.baslik.setGeometry(QtCore.QRect(10, 70, 411, 31))
        self.baslik.setStyleSheet("font-size:20px;\n"
"color:white;\n"
"background:transparent;")
        self.baslik.setAlignment(QtCore.Qt.AlignCenter)
        self.baslik.setObjectName("baslik")
        self.username = QtWidgets.QLineEdit(self.frame)
        self.username.setGeometry(QtCore.QRect(30, 110, 371, 61))
        self.username.setMaxLength(18)
        self.username.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.username.setCursorPosition(18)
        self.username.setClearButtonEnabled(True)
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(30, 200, 371, 61))
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.remember_me = QtWidgets.QCheckBox(self.frame)
        self.remember_me.setGeometry(QtCore.QRect(30, 290, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.remember_me.setFont(font)
        self.remember_me.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.remember_me.setStyleSheet("")
        self.remember_me.setObjectName("remember_me")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(150, 290, 1, 18))
        self.line.setStyleSheet("background:white;")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btn_newAccount = QtWidgets.QPushButton(self.frame)
        self.btn_newAccount.setGeometry(QtCore.QRect(160, 290, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_newAccount.setFont(font)
        self.btn_newAccount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_newAccount.setStyleSheet("QPushButton{\n"
"background:transparent\n"
"}\n"
"\n"
"QPushButton{\n"
"color:silver;\n"
"background:transparent\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"}\n"
"\n"
"")
        self.btn_newAccount.setAutoDefault(False)
        self.btn_newAccount.setObjectName("btn_newAccount")
        self.btn_sign = QtWidgets.QPushButton(self.frame)
        self.btn_sign.setGeometry(QtCore.QRect(30, 330, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_sign.setFont(font)
        self.btn_sign.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_sign.setDefault(True)
        self.btn_sign.setFlat(True)
        self.btn_sign.setObjectName("btn_sign")
        self.frame_3 = QtWidgets.QFrame(Login)
        self.frame_3.setGeometry(QtCore.QRect(-1, -1, 451, 501))
        self.frame_3.setStyleSheet("QFrame{\n"
"    background-image: url(:/images/img/background/login_2.jpg);\n"
"    border-top-left-radius:0px;\n"
"    border-top-right-radius:0px;\n"
"    border-bottom-left-radius:25px;\n"
"    border-bottom-right-radius:25px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_2 = QtWidgets.QFrame(Login)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 451, 41))
        self.frame_2.setStyleSheet("QFrame{\n"
"background:rgba(0,0,0,0.60);\n"
"}\n"
"QFrame{\n"
"\n"
"border-radius:none;\n"
"\n"
"}\n"
"\n"
"QFrame:hover{\n"
"background:rgba(0,0,0,0.75);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_2)
        self.btn_minimize.setGeometry(QtCore.QRect(370, 0, 40, 38))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.btn_minimize.setFont(font)
        self.btn_minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_minimize.setStyleSheet("QPushButton{\n"
"background:rgba(0, 0, 0,0.15);\n"
"border-radius:none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background:rgba(0, 0, 0,0.6)\n"
"}")
        self.btn_minimize.setObjectName("btn_minimize")
        self.btn_close = QtWidgets.QPushButton(self.frame_2)
        self.btn_close.setGeometry(QtCore.QRect(410, 0, 40, 38))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_close.setFont(font)
        self.btn_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_close.setStyleSheet("QPushButton{\n"
"background:rgba(0, 0, 0,0.15);\n"
"color:silver;\n"
"\n"
"border-radius:none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background:red;\n"
"color:white\n"
"}")
        self.btn_close.setObjectName("btn_close")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"color:silver;\n"
"background:transparent;")
        self.label_2.setObjectName("label_2")
        self.frame_3.raise_()
        self.frame.raise_()
        self.frame_2.raise_()

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.baslik_2.setText(_translate("Login", "RESTORAN NOMI"))
        self.baslik.setText(_translate("Login", "Buyurtma berish tizimi"))
        self.username.setInputMask(_translate("Login", "+\\9\\9\\8(99)-999-99-99"))
        self.username.setText(_translate("Login", "+998()---"))
        self.username.setPlaceholderText(_translate("Login", "Telefon raqam"))
        self.password.setPlaceholderText(_translate("Login", "Parol"))
        self.remember_me.setText(_translate("Login", "Eslab qolish"))
        self.btn_newAccount.setText(_translate("Login", "Ro\'yxatdan o\'tish"))
        self.btn_sign.setText(_translate("Login", "Kirish"))
        self.btn_minimize.setText(_translate("Login", "_"))
        self.btn_close.setText(_translate("Login", "✕"))
        self.label_2.setText(_translate("Login", "Kirish"))
import images_rc
