# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 800)
        MainWindow.setMinimumSize(QtCore.QSize(880, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1300, 800))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QStatusBar{\n"
"border: none;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame_2.setStyleSheet("QFrame{\n"
"background:rgba(0,0,0,0.8);\n"
"}\n"
"QFrame{\n"
"\n"
"border-radius:none;\n"
"\n"
"}\n"
"\n"
"QFrame:hover{\n"
"background:rgba(0,0,0,0.9);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMinimumSize(QtCore.QSize(40, 0))
        self.label_2.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"color:silver;\n"
"background:transparent;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_admin = QtWidgets.QLabel(self.frame_2)
        self.label_admin.setStyleSheet("\n"
"color:silver;\n"
"background:transparent;")
        self.label_admin.setObjectName("label_admin")
        self.horizontalLayout.addWidget(self.label_admin)
        self.btn_minimize = QtWidgets.QPushButton(self.frame_2)
        self.btn_minimize.setMinimumSize(QtCore.QSize(41, 40))
        self.btn_minimize.setMaximumSize(QtCore.QSize(41, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.btn_minimize.setFont(font)
        self.btn_minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_minimize.setStyleSheet("QPushButton{\n"
"background:rgba(0, 0, 0,0.15);\n"
"border-radius:none;\n"
"color: white;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background:rgba(0, 0, 0,0.6)\n"
"}")
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout.addWidget(self.btn_minimize)
        self.btn_close = QtWidgets.QPushButton(self.frame_2)
        self.btn_close.setMinimumSize(QtCore.QSize(41, 40))
        self.btn_close.setMaximumSize(QtCore.QSize(41, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_close.setFont(font)
        self.btn_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_close.setStyleSheet("QPushButton{\n"
"background:rgba(0, 0, 0,0.15);\n"
"color:silver;\n"
"\n"
"border-radius:none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background:red;\n"
"color:white\n"
"}")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.verticalLayout.addWidget(self.frame_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QWidget{\n"
"background-image: url(:/images/img/back_1.jpg);\n"
"}\n"
"QWidget{\n"
"  font-size: 20px;\n"
"  font-weight: 600;\n"
"  color: transparent;\n"
"  background-clip: text;\n"
"  border: none;\n"
"}\n"
"QTabWidget::tab-bar {\n"
"\n"
" }\n"
"QTabBar{\n"
"\n"
"}\n"
"QTabBar::tab{\n"
"align-items: center;\n"
"min-width: 200px;\n"
"  background: rgba(0,0,0,0.6);\n"
"  color: white;\n"
"  padding: 10px;\n"
"}\n"
"\n"
" QTabBar::tab:last{\n"
" background: rgba(19,128,195, 0.9);\n"
"\n"
" }\n"
"\n"
" QTabBar::tab:selected {\n"
"  background: rgba(195,63,11,0.6);\n"
" }\n"
" QTabBar::tab:hover {\n"
"  background: rgba(36,32,33, 0.1);\n"
" }\n"
"QFrame{\n"
"    background: rgba(0,0,0,0.4);\n"
"}\n"
"QFrame:hover{\n"
"    background: rgba(0,0,0,0.7);\n"
"}\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_products = QtWidgets.QWidget()
        self.tab_products.setObjectName("tab_products")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_products)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_products)
        self.scrollArea.setStyleSheet("QFrame{\n"
"background: transparent;\n"
"}\n"
"QWidget{\n"
"background: transparent;\n"
"}\n"
"QPushButton{\n"
"    background:rgb(83, 152, 255);\n"
"    border-radius:10px;\n"
"    color:#fff;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:none;\n"
"    background:rgb(68, 117, 222)\n"
"}\n"
"\n"
"QLabel{\n"
"font-size: 14px;\n"
"text-align: center;\n"
"color: white;\n"
"padding: 2px;\n"
"border-radius: 10px;\n"
"}\n"
"QLabel:hover{\n"
"background: rgba(255,255,255,0.3);\n"
"border: 1px solid rgb(68, 117, 222);\n"
"border-radius: 5px;\n"
"}\n"
"QScrollBar:vertical\n"
"    {\n"
"        background-color: #2A2929;\n"
"        width: 15px;\n"
"        margin: 15px 3px 15px 3px;\n"
"        border: 1px transparent #2A2929;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical\n"
"    {\n"
"        background-color: rgba(195,63,11,0.8);        /* #605F5F; */\n"
"        min-height: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/down_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"    {\n"
"        background: none;\n"
"    }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 930, 716))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.gridProducts = QtWidgets.QGridLayout()
        self.gridProducts.setObjectName("gridProducts")
        self.gridLayout.addLayout(self.gridProducts, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_products)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(370, 0))
        self.scrollArea_2.setStyleSheet("QFrame{\n"
"background: transparent;\n"
"}\n"
"QWidget{\n"
"background: transparent;\n"
"}\n"
"QPushButton{\n"
"    background:rgb(83, 152, 255);\n"
"    border-radius:10px;\n"
"    color:#fff;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:none;\n"
"    background:rgb(68, 117, 222)\n"
"}\n"
"\n"
"QLabel{\n"
"font-size: 14px;\n"
"text-align: center;\n"
"color: white;\n"
"padding: 2px;\n"
"border-radius: 10px;\n"
"}\n"
"QLabel:hover{\n"
"background: rgba(255,255,255,0.3);\n"
"border: 1px solid rgb(68, 117, 222);\n"
"border-radius: 5px;\n"
"}\n"
"QScrollBar:vertical\n"
"    {\n"
"        background-color: #2A2929;\n"
"        width: 15px;\n"
"        margin: 15px 3px 15px 3px;\n"
"        border: 1px transparent #2A2929;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical\n"
"    {\n"
"        background-color: rgba(195,63,11,0.8);        /* #605F5F; */\n"
"        min-height: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/down_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"    {\n"
"        background: none;\n"
"    }")
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 355, 716))
        self.scrollAreaWidgetContents_3.setStyleSheet("")
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formProductsInfo = QtWidgets.QFormLayout()
        self.formProductsInfo.setObjectName("formProductsInfo")
        self.verticalLayout_2.addLayout(self.formProductsInfo)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_2.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_products, "")
        self.tab_users = QtWidgets.QWidget()
        self.tab_users.setObjectName("tab_users")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_users)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_users)
        self.scrollArea_3.setStyleSheet("QFrame{\n"
"background: transparent;\n"
"}\n"
"QWidget{\n"
"background: transparent;\n"
"}\n"
"QPushButton{\n"
"    background:rgb(83, 152, 255);\n"
"    border-radius:10px;\n"
"    color:#fff;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:none;\n"
"    background:rgb(68, 117, 222)\n"
"}\n"
"\n"
"QLabel{\n"
"font-size: 14px;\n"
"text-align: center;\n"
"color: white;\n"
"padding: 2px;\n"
"border-radius: 10px;\n"
"}\n"
"QLabel:hover{\n"
"background: rgba(255,255,255,0.3);\n"
"border: 1px solid rgb(68, 117, 222);\n"
"border-radius: 5px;\n"
"}\n"
"QScrollBar:vertical\n"
"    {\n"
"        background-color: #2A2929;\n"
"        width: 15px;\n"
"        margin: 15px 3px 15px 3px;\n"
"        border: 1px transparent #2A2929;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical\n"
"    {\n"
"        background-color: rgba(195,63,11,0.8);        /* #605F5F; */\n"
"        min-height: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/down_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"    {\n"
"        background: none;\n"
"    }")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 900, 716))
        self.scrollAreaWidgetContents_4.setStyleSheet("QFrame{\n"
"background: transparent;\n"
"}\n"
"QWidget{\n"
"background: transparent;\n"
"}\n"
"QPushButton{\n"
"    background:rgb(83, 152, 255);\n"
"    border-radius:10px;\n"
"    color:#fff;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:none;\n"
"    background:rgb(68, 117, 222)\n"
"}\n"
"\n"
"QLabel{\n"
"font-size: 14px;\n"
"text-align: center;\n"
"color: white;\n"
"padding: 2px;\n"
"border-radius: 10px;\n"
"}\n"
"QLabel:hover{\n"
"background: rgba(255,255,255,0.3);\n"
"border: 1px solid rgb(68, 117, 222);\n"
"border-radius: 5px;\n"
"}\n"
"QScrollBar:vertical\n"
"    {\n"
"        background-color: #2A2929;\n"
"        width: 15px;\n"
"        margin: 15px 3px 15px 3px;\n"
"        border: 1px transparent #2A2929;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical\n"
"    {\n"
"        background-color: rgba(195,63,11,0.8);        /* #605F5F; */\n"
"        min-height: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/down_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"    {\n"
"        background: none;\n"
"    }")
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridUsers = QtWidgets.QGridLayout()
        self.gridUsers.setObjectName("gridUsers")
        self.gridLayout_3.addLayout(self.gridUsers, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_3.addWidget(self.scrollArea_3)
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tab_users)
        self.scrollArea_4.setMinimumSize(QtCore.QSize(400, 0))
        self.scrollArea_4.setMaximumSize(QtCore.QSize(400, 16777215))
        self.scrollArea_4.setStyleSheet("QFrame{\n"
"background: transparent;\n"
"}\n"
"QWidget{\n"
"background: transparent;\n"
"}\n"
"QPushButton{\n"
"    background:rgb(83, 152, 255);\n"
"    border-radius:10px;\n"
"    color:#fff;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:none;\n"
"    background:rgb(68, 117, 222)\n"
"}\n"
"\n"
"QLabel{\n"
"font-size: 14px;\n"
"text-align: center;\n"
"color: white;\n"
"padding: 2px;\n"
"border-radius: 10px;\n"
"}\n"
"QLabel:hover{\n"
"background: rgba(255,255,255,0.3);\n"
"border: 1px solid rgb(68, 117, 222);\n"
"border-radius: 5px;\n"
"}\n"
"QScrollBar:vertical\n"
"    {\n"
"        background-color: #2A2929;\n"
"        width: 15px;\n"
"        margin: 15px 3px 15px 3px;\n"
"        border: 1px transparent #2A2929;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical\n"
"    {\n"
"        background-color: rgba(195,63,11,0.8);        /* #605F5F; */\n"
"        min-height: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/down_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"    {\n"
"        background: none;\n"
"    }")
        self.scrollArea_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 385, 716))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formUsersInfo = QtWidgets.QFormLayout()
        self.formUsersInfo.setObjectName("formUsersInfo")
        self.verticalLayout_3.addLayout(self.formUsersInfo)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_5)
        self.horizontalLayout_3.addWidget(self.scrollArea_4)
        self.tabWidget.addTab(self.tab_users, "")
        self.tab_admin = QtWidgets.QWidget()
        self.tab_admin.setObjectName("tab_admin")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_admin)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scrollArea_6 = QtWidgets.QScrollArea(self.tab_admin)
        self.scrollArea_6.setStyleSheet("QFrame{\n"
"background: transparent;\n"
"}\n"
"QWidget{\n"
"background: transparent;\n"
"}\n"
"QPushButton{\n"
"    background:rgb(83, 152, 255);\n"
"    border-radius:10px;\n"
"    color:#fff;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:none;\n"
"    background:rgb(68, 117, 222)\n"
"}\n"
"\n"
"QLabel{\n"
"font-size: 14px;\n"
"text-align: center;\n"
"color: white;\n"
"padding: 2px;\n"
"border-radius: 10px;\n"
"}\n"
"QLabel:hover{\n"
"background: rgba(255,255,255,0.3);\n"
"border: 1px solid rgb(68, 117, 222);\n"
"border-radius: 5px;\n"
"}\n"
"QScrollBar:vertical\n"
"    {\n"
"        background-color: #2A2929;\n"
"        width: 15px;\n"
"        margin: 15px 3px 15px 3px;\n"
"        border: 1px transparent #2A2929;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical\n"
"    {\n"
"        background-color: rgba(195,63,11,0.8);        /* #605F5F; */\n"
"        min-height: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/down_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"    {\n"
"        background: none;\n"
"    }")
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 900, 716))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridAdmins = QtWidgets.QGridLayout()
        self.gridAdmins.setObjectName("gridAdmins")
        self.gridLayout_5.addLayout(self.gridAdmins, 0, 0, 1, 1)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_7)
        self.horizontalLayout_5.addWidget(self.scrollArea_6)
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tab_admin)
        self.scrollArea_5.setMinimumSize(QtCore.QSize(400, 0))
        self.scrollArea_5.setMaximumSize(QtCore.QSize(400, 16777215))
        self.scrollArea_5.setStyleSheet("QFrame{\n"
"background: transparent;\n"
"}\n"
"QWidget{\n"
"background: transparent;\n"
"}\n"
"QPushButton{\n"
"    background:rgb(83, 152, 255);\n"
"    border-radius:10px;\n"
"    color:#fff;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:none;\n"
"    background:rgb(68, 117, 222)\n"
"}\n"
"\n"
"QLabel{\n"
"font-size: 14px;\n"
"text-align: center;\n"
"color: white;\n"
"padding: 2px;\n"
"border-radius: 10px;\n"
"}\n"
"QLabel:hover{\n"
"background: rgba(255,255,255,0.3);\n"
"border: 1px solid rgb(68, 117, 222);\n"
"border-radius: 5px;\n"
"}\n"
"QScrollBar:vertical\n"
"    {\n"
"        background-color: #2A2929;\n"
"        width: 15px;\n"
"        margin: 15px 3px 15px 3px;\n"
"        border: 1px transparent #2A2929;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical\n"
"    {\n"
"        background-color: rgba(195,63,11,0.8);        /* #605F5F; */\n"
"        min-height: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/down_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"    {\n"
"        background: none;\n"
"    }")
        self.scrollArea_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 385, 716))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formAdminsInfo = QtWidgets.QFormLayout()
        self.formAdminsInfo.setObjectName("formAdminsInfo")
        self.verticalLayout_4.addLayout(self.formAdminsInfo)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_6)
        self.horizontalLayout_5.addWidget(self.scrollArea_5)
        self.tabWidget.addTab(self.tab_admin, "")
        self.tab_profil = QtWidgets.QWidget()
        self.tab_profil.setObjectName("tab_profil")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_profil)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame = QtWidgets.QFrame(self.tab_profil)
        self.frame.setMinimumSize(QtCore.QSize(700, 0))
        self.frame.setMaximumSize(QtCore.QSize(700, 16777215))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setStyleSheet("QWidget{\n"
"  font-size: 14px;\n"
"  font-weight: 500;\n"
"  color: transparent;\n"
"  background-clip: text;\n"
"  border: none;\n"
"}\n"
"QLineEdit{\n"
"    font-size:18px;;\n"
"    color:white;\n"
"    border:none;\n"
"    background:transparent;\n"
"    border-bottom:1px solid white;\n"
"}\n"
"\n"
"QLineEdit:hover, QTextEdit:hover{\n"
"    background:rgba(0,0,0,0.04);\n"
"}\n"
"QTextEdit{\n"
"    font-size:18px;;\n"
"    color:white;\n"
"    background:transparent;\n"
"    border:1px solid white;\n"
"}\n"
"QLabel{\n"
"color: white;\n"
"padding: 2px;\n"
"background: transparent;\n"
"font-size: 13px;\n"
"}\n"
"QPushButton{\n"
"background:rgba(0, 0, 0,0.6);\n"
"border-radius:none;\n"
"color: white;\n"
"}\n"
"QPushButton:hover{\n"
"background:rgba(0, 0, 0,0.6)\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(351, 45))
        self.frame_3.setMaximumSize(QtCore.QSize(450, 51))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnCancel_2 = QtWidgets.QPushButton(self.frame_3)
        self.btnCancel_2.setMaximumSize(QtCore.QSize(200, 51))
        self.btnCancel_2.setStyleSheet("QPushButton:hover{\n"
"background: rgba(231,30,21,0.6);\n"
"}")
        self.btnCancel_2.setObjectName("btnCancel_2")
        self.horizontalLayout_7.addWidget(self.btnCancel_2)
        self.btnOk_2 = QtWidgets.QPushButton(self.frame_3)
        self.btnOk_2.setMaximumSize(QtCore.QSize(200, 51))
        self.btnOk_2.setStyleSheet("QPushButton:hover{\n"
"background:rgb(68, 117, 222)\n"
"}")
        self.btnOk_2.setObjectName("btnOk_2")
        self.horizontalLayout_7.addWidget(self.btnOk_2)
        self.gridLayout_6.addWidget(self.frame_3, 7, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setMinimumSize(QtCore.QSize(450, 0))
        self.widget.setMaximumSize(QtCore.QSize(450, 45))
        self.widget.setStyleSheet("background: transparent;")
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.edit_name = QtWidgets.QLineEdit(self.widget)
        self.edit_name.setMinimumSize(QtCore.QSize(220, 45))
        self.edit_name.setMaximumSize(QtCore.QSize(220, 51))
        self.edit_name.setText("")
        self.edit_name.setMaxLength(24)
        self.edit_name.setClearButtonEnabled(True)
        self.edit_name.setObjectName("edit_name")
        self.horizontalLayout_6.addWidget(self.edit_name)
        self.edit_surname = QtWidgets.QLineEdit(self.widget)
        self.edit_surname.setMinimumSize(QtCore.QSize(220, 45))
        self.edit_surname.setMaximumSize(QtCore.QSize(220, 51))
        self.edit_surname.setText("")
        self.edit_surname.setMaxLength(24)
        self.edit_surname.setFrame(True)
        self.edit_surname.setClearButtonEnabled(True)
        self.edit_surname.setObjectName("edit_surname")
        self.horizontalLayout_6.addWidget(self.edit_surname)
        self.gridLayout_6.addWidget(self.widget, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMinimumSize(QtCore.QSize(351, 18))
        self.label_3.setMaximumSize(QtCore.QSize(450, 18))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 5, 0, 1, 1)
        self.edit_address = QtWidgets.QTextEdit(self.frame)
        self.edit_address.setMinimumSize(QtCore.QSize(351, 60))
        self.edit_address.setMaximumSize(QtCore.QSize(450, 80))
        self.edit_address.setObjectName("edit_address")
        self.gridLayout_6.addWidget(self.edit_address, 6, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_4.setMaximumSize(QtCore.QSize(450, 51))
        self.frame_4.setStyleSheet("QRadioButton{\n"
"background: transparent;\n"
"font-size: 14px;\n"
"color: white;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(9)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.edit_phone = QtWidgets.QLineEdit(self.frame_4)
        self.edit_phone.setMinimumSize(QtCore.QSize(220, 45))
        self.edit_phone.setMaximumSize(QtCore.QSize(220, 51))
        self.edit_phone.setMaxLength(18)
        self.edit_phone.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.edit_phone.setCursorPosition(18)
        self.edit_phone.setClearButtonEnabled(True)
        self.edit_phone.setObjectName("edit_phone")
        self.horizontalLayout_8.addWidget(self.edit_phone)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMinimumSize(QtCore.QSize(220, 45))
        self.frame_6.setMaximumSize(QtCore.QSize(220, 51))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.radio_male = QtWidgets.QRadioButton(self.frame_6)
        self.radio_male.setMinimumSize(QtCore.QSize(100, 0))
        self.radio_male.setMaximumSize(QtCore.QSize(100, 16777215))
        self.radio_male.setObjectName("radio_male")
        self.horizontalLayout_9.addWidget(self.radio_male)
        self.radio_female = QtWidgets.QRadioButton(self.frame_6)
        self.radio_female.setMinimumSize(QtCore.QSize(100, 0))
        self.radio_female.setMaximumSize(QtCore.QSize(100, 16777215))
        self.radio_female.setObjectName("radio_female")
        self.horizontalLayout_9.addWidget(self.radio_female)
        self.horizontalLayout_8.addWidget(self.frame_6)
        self.gridLayout_6.addWidget(self.frame_4, 4, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 220))
        self.frame_5.setStyleSheet("QPushButton{\n"
"background: rgba(255,255,255,0.3);\n"
"border-radius: 7px;\n"
"border: 2px solid rgba(255,255,255,0.7);\n"
"/*rgb(68, 117, 222)*/\n"
"}\n"
"QPushButton:hover{\n"
"background: rgba(255,255,255,0.5);\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_2.setContentsMargins(10, 0, 10, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.avatar = QtWidgets.QLabel(self.frame_5)
        self.avatar.setMinimumSize(QtCore.QSize(220, 0))
        self.avatar.setMaximumSize(QtCore.QSize(220, 220))
        self.avatar.setText("")
        self.avatar.setAlignment(QtCore.Qt.AlignCenter)
        self.avatar.setWordWrap(False)
        self.avatar.setOpenExternalLinks(False)
        self.avatar.setObjectName("avatar")
        self.gridLayout_2.addWidget(self.avatar, 0, 0, 3, 1)
        self.btn_previous = QtWidgets.QPushButton(self.frame_5)
        self.btn_previous.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_previous.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_previous.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/img/profile/previous .png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_previous.setIcon(icon)
        self.btn_previous.setIconSize(QtCore.QSize(48, 48))
        self.btn_previous.setObjectName("btn_previous")
        self.gridLayout_2.addWidget(self.btn_previous, 1, 1, 1, 1)
        self.btn_template = QtWidgets.QPushButton(self.frame_5)
        self.btn_template.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_template.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_template.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/img/profile/global.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_template.setIcon(icon1)
        self.btn_template.setIconSize(QtCore.QSize(48, 48))
        self.btn_template.setObjectName("btn_template")
        self.gridLayout_2.addWidget(self.btn_template, 1, 2, 1, 1)
        self.btn_next = QtWidgets.QPushButton(self.frame_5)
        self.btn_next.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_next.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_next.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/img/profile/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next.setIcon(icon2)
        self.btn_next.setIconSize(QtCore.QSize(48, 48))
        self.btn_next.setObjectName("btn_next")
        self.gridLayout_2.addWidget(self.btn_next, 1, 3, 1, 1)
        self.btn_edit = QtWidgets.QPushButton(self.frame_5)
        self.btn_edit.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_edit.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_edit.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/img/profile/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_edit.setIcon(icon3)
        self.btn_edit.setIconSize(QtCore.QSize(48, 48))
        self.btn_edit.setObjectName("btn_edit")
        self.gridLayout_2.addWidget(self.btn_edit, 0, 1, 1, 1)
        self.btn_remove = QtWidgets.QPushButton(self.frame_5)
        self.btn_remove.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_remove.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_remove.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/img/profile/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_remove.setIcon(icon4)
        self.btn_remove.setIconSize(QtCore.QSize(48, 48))
        self.btn_remove.setObjectName("btn_remove")
        self.gridLayout_2.addWidget(self.btn_remove, 0, 2, 1, 1)
        self.btn_edit_2 = QtWidgets.QPushButton(self.frame_5)
        self.btn_edit_2.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_edit_2.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_edit_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/img/profile/sign.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_edit_2.setIcon(icon5)
        self.btn_edit_2.setIconSize(QtCore.QSize(48, 48))
        self.btn_edit_2.setObjectName("btn_edit_2")
        self.gridLayout_2.addWidget(self.btn_edit_2, 2, 2, 1, 1)
        self.btn_updatepassword = QtWidgets.QPushButton(self.frame_5)
        self.btn_updatepassword.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_updatepassword.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_updatepassword.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/img/profile/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_updatepassword.setIcon(icon6)
        self.btn_updatepassword.setIconSize(QtCore.QSize(48, 48))
        self.btn_updatepassword.setObjectName("btn_updatepassword")
        self.gridLayout_2.addWidget(self.btn_updatepassword, 2, 3, 1, 1)
        self.gridLayout_6.addWidget(self.frame_5, 3, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.frame)
        self.tabWidget.addTab(self.tab_profil, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Asosiy"))
        self.label_admin.setText(_translate("MainWindow", "TextLabel"))
        self.btn_minimize.setText(_translate("MainWindow", "_"))
        self.btn_close.setText(_translate("MainWindow", "✕"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_products), _translate("MainWindow", "Mahsulotlar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_users), _translate("MainWindow", "Foydalanuvchilar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_admin), _translate("MainWindow", "Adminlar"))
        self.btnCancel_2.setText(_translate("MainWindow", "Bekor qilish"))
        self.btnOk_2.setText(_translate("MainWindow", "Saqlash"))
        self.edit_name.setPlaceholderText(_translate("MainWindow", "Ism"))
        self.edit_surname.setPlaceholderText(_translate("MainWindow", "Familiya"))
        self.label_3.setText(_translate("MainWindow", "Manzil:"))
        self.edit_phone.setInputMask(_translate("MainWindow", "+\\9\\9\\8(99)-999-99-99"))
        self.edit_phone.setText(_translate("MainWindow", "+998()---"))
        self.edit_phone.setPlaceholderText(_translate("MainWindow", "Telefon raqam"))
        self.radio_male.setText(_translate("MainWindow", "Erkak"))
        self.radio_female.setText(_translate("MainWindow", "Ayol"))
        self.btn_previous.setToolTip(_translate("MainWindow", "Oldingi shavlon avatar"))
        self.btn_template.setToolTip(_translate("MainWindow", "Shablon avatar"))
        self.btn_next.setToolTip(_translate("MainWindow", "Keyingi shablon avatar"))
        self.btn_edit.setToolTip(_translate("MainWindow", "Avatar tanlash"))
        self.btn_remove.setToolTip(_translate("MainWindow", "Default avatarni tanlash"))
        self.btn_edit_2.setToolTip(_translate("MainWindow", "Taxrirlash"))
        self.btn_updatepassword.setToolTip(_translate("MainWindow", "Parol almashtirish"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_profil), _translate("MainWindow", "Profil"))
import images_rc
