# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registration(object):
    def setupUi(self, Registration):
        Registration.setObjectName("Registration")
        Registration.resize(620, 650)
        Registration.setMinimumSize(QtCore.QSize(620, 650))
        Registration.setMaximumSize(QtCore.QSize(620, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/img/icon/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Registration.setWindowIcon(icon)
        Registration.setStyleSheet("QFrame{\n"
"    background:rgba(0,0,0,0.4);\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background:rgba(0,0,0,0.6);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    font-size:25px;;\n"
"    color:white;\n"
"    border:none;\n"
"    background:transparent;\n"
"    border-bottom:1px solid white;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background:rgba(0,0,0,0.04);\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    background:rgb(83, 152, 255);\n"
"    border-radius:10px;\n"
"    color:#fff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:none;\n"
"    background:rgb(68, 117, 222)\n"
"}\n"
"\n"
"QCheckBox{\n"
"    color:silver;\n"
"    background:transparent\n"
"}\n"
"QCheckBox:hover{\n"
"    color:white;\n"
"}")
        self.frame_2 = QtWidgets.QFrame(Registration)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 621, 38))
        self.frame_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame_2.setStyleSheet("QFrame{\n"
"background:rgba(0,0,0,0.60);\n"
"}\n"
"QFrame{\n"
"\n"
"border-radius:none;\n"
"\n"
"}\n"
"\n"
"QFrame:hover{\n"
"background:rgba(0,0,0,0.75);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btn_close = QtWidgets.QPushButton(self.frame_2)
        self.btn_close.setGeometry(QtCore.QRect(580, 0, 40, 38))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_close.setFont(font)
        self.btn_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_close.setStyleSheet("QPushButton{\n"
"background:rgba(0, 0, 0,0.15);\n"
"color:silver;\n"
"\n"
"border-radius:none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background:red;\n"
"color:white\n"
"}")
        self.btn_close.setObjectName("btn_close")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_2)
        self.btn_minimize.setGeometry(QtCore.QRect(540, 0, 40, 38))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.btn_minimize.setFont(font)
        self.btn_minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_minimize.setStyleSheet("QPushButton{\n"
"background:rgba(0, 0, 0,0.15);\n"
"border-radius:none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background:rgba(0, 0, 0,0.6)\n"
"}")
        self.btn_minimize.setObjectName("btn_minimize")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"color:silver;\n"
"background:transparent;")
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(Registration)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 621, 651))
        self.widget.setStyleSheet("QWidget{\n"
"    border-bottom-left-radius: 25px;\n"
"    border-bottom-right-radius: 25px;\n"
"    background-image: url(:/images/img/background/reg_1.jpg);\n"
"}")
        self.widget.setObjectName("widget")
        self.frame = QtWidgets.QFrame(Registration)
        self.frame.setGeometry(QtCore.QRect(30, 70, 560, 560))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.name_2 = QtWidgets.QLineEdit(self.frame)
        self.name_2.setGeometry(QtCore.QRect(20, 131, 250, 61))
        self.name_2.setText("")
        self.name_2.setMaxLength(24)
        self.name_2.setClearButtonEnabled(True)
        self.name_2.setObjectName("name_2")
        self.baslik_3 = QtWidgets.QLabel(self.frame)
        self.baslik_3.setGeometry(QtCore.QRect(-1, 10, 561, 71))
        self.baslik_3.setStyleSheet("font-size:40px;\n"
"color:white;\n"
"background:transparent;")
        self.baslik_3.setAlignment(QtCore.Qt.AlignCenter)
        self.baslik_3.setObjectName("baslik_3")
        self.baslik_4 = QtWidgets.QLabel(self.frame)
        self.baslik_4.setGeometry(QtCore.QRect(5, 80, 551, 21))
        self.baslik_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.baslik_4.setStyleSheet("font-size:18px;\n"
"color:white;\n"
"background:transparent;")
        self.baslik_4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.baslik_4.setTextFormat(QtCore.Qt.AutoText)
        self.baslik_4.setScaledContents(False)
        self.baslik_4.setAlignment(QtCore.Qt.AlignCenter)
        self.baslik_4.setOpenExternalLinks(True)
        self.baslik_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.baslik_4.setObjectName("baslik_4")
        self.surname_2 = QtWidgets.QLineEdit(self.frame)
        self.surname_2.setGeometry(QtCore.QRect(290, 130, 250, 61))
        self.surname_2.setText("")
        self.surname_2.setMaxLength(24)
        self.surname_2.setFrame(True)
        self.surname_2.setClearButtonEnabled(True)
        self.surname_2.setObjectName("surname_2")
        self.password_3 = QtWidgets.QLineEdit(self.frame)
        self.password_3.setGeometry(QtCore.QRect(20, 340, 521, 61))
        self.password_3.setText("")
        self.password_3.setMaxLength(24)
        self.password_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_3.setClearButtonEnabled(True)
        self.password_3.setObjectName("password_3")
        self.password_2 = QtWidgets.QLineEdit(self.frame)
        self.password_2.setGeometry(QtCore.QRect(20, 270, 521, 61))
        self.password_2.setText("")
        self.password_2.setMaxLength(24)
        self.password_2.setFrame(True)
        self.password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_2.setClearButtonEnabled(True)
        self.password_2.setObjectName("password_2")
        self.phone_2 = QtWidgets.QLineEdit(self.frame)
        self.phone_2.setGeometry(QtCore.QRect(20, 200, 521, 61))
        self.phone_2.setMaxLength(18)
        self.phone_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.phone_2.setClearButtonEnabled(True)
        self.phone_2.setObjectName("phone_2")
        self.btn_createAccount_2 = QtWidgets.QPushButton(self.frame)
        self.btn_createAccount_2.setGeometry(QtCore.QRect(90, 450, 400, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_createAccount_2.setFont(font)
        self.btn_createAccount_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_createAccount_2.setObjectName("btn_createAccount_2")
        self.widget.raise_()
        self.frame_2.raise_()
        self.frame.raise_()

        self.retranslateUi(Registration)
        QtCore.QMetaObject.connectSlotsByName(Registration)
        Registration.setTabOrder(self.name_2, self.surname_2)
        Registration.setTabOrder(self.surname_2, self.phone_2)
        Registration.setTabOrder(self.phone_2, self.password_2)
        Registration.setTabOrder(self.password_2, self.password_3)
        Registration.setTabOrder(self.password_3, self.btn_createAccount_2)
        Registration.setTabOrder(self.btn_createAccount_2, self.btn_close)
        Registration.setTabOrder(self.btn_close, self.btn_minimize)

    def retranslateUi(self, Registration):
        _translate = QtCore.QCoreApplication.translate
        Registration.setWindowTitle(_translate("Registration", "Registration"))
        self.btn_close.setText(_translate("Registration", "✕"))
        self.btn_minimize.setText(_translate("Registration", "_"))
        self.label_2.setText(_translate("Registration", "Ro\'yxatdan o\'tish"))
        self.name_2.setPlaceholderText(_translate("Registration", "Ism"))
        self.baslik_3.setText(_translate("Registration", "RESTORAN NOMI"))
        self.baslik_4.setText(_translate("Registration", "Buyurtma berish tizimi"))
        self.surname_2.setPlaceholderText(_translate("Registration", "Familiya"))
        self.password_3.setPlaceholderText(_translate("Registration", "Parol takror"))
        self.password_2.setPlaceholderText(_translate("Registration", "Parol"))
        self.phone_2.setInputMask(_translate("Registration", "+\\9\\9\\8(99)-999-99-99"))
        self.phone_2.setText(_translate("Registration", "+998()---"))
        self.phone_2.setPlaceholderText(_translate("Registration", "Telefon raqam"))
        self.btn_createAccount_2.setText(_translate("Registration", "Ro\'yxatdan o\'tish"))
        self.btn_createAccount_2.setShortcut(_translate("Registration", "Return"))
import images_rc
