# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UpdatePassword(object):
    def setupUi(self, UpdatePassword):
        UpdatePassword.setObjectName("UpdatePassword")
        UpdatePassword.resize(450, 500)
        UpdatePassword.setMinimumSize(QtCore.QSize(450, 500))
        UpdatePassword.setMaximumSize(QtCore.QSize(450, 500))
        UpdatePassword.setStyleSheet("QFrame{\n"
"    background:rgba(0,0,0,0.4);\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background:rgba(0,0,0,0.6);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    font-size:25px;;\n"
"    color:white;\n"
"    border:none;\n"
"    background:transparent;\n"
"    border-bottom:1px solid white;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background:rgba(0,0,0,0.04);\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    background:rgb(83, 152, 255);\n"
"    border-radius:10px;\n"
"    color:#fff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:none;\n"
"    background:rgb(68, 117, 222)\n"
"}\n"
"\n"
"QCheckBox{\n"
"    color:silver;\n"
"    background:transparent\n"
"}\n"
"QCheckBox:hover{\n"
"    color:white;\n"
"}")
        self.frame = QtWidgets.QFrame(UpdatePassword)
        self.frame.setGeometry(QtCore.QRect(10, 70, 431, 411))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.baslik_2 = QtWidgets.QLabel(self.frame)
        self.baslik_2.setGeometry(QtCore.QRect(10, 20, 411, 41))
        self.baslik_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.baslik_2.setStyleSheet("font-size:30px;\n"
"color:white;\n"
"background:transparent;\n"
"text-align: center;")
        self.baslik_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.baslik_2.setTextFormat(QtCore.Qt.AutoText)
        self.baslik_2.setScaledContents(False)
        self.baslik_2.setAlignment(QtCore.Qt.AlignCenter)
        self.baslik_2.setOpenExternalLinks(True)
        self.baslik_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.baslik_2.setObjectName("baslik_2")
        self.old_password = QtWidgets.QLineEdit(self.frame)
        self.old_password.setGeometry(QtCore.QRect(40, 90, 351, 51))
        self.old_password.setMinimumSize(QtCore.QSize(351, 45))
        self.old_password.setMaximumSize(QtCore.QSize(220, 51))
        self.old_password.setText("")
        self.old_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.old_password.setClearButtonEnabled(True)
        self.old_password.setObjectName("old_password")
        self.password_1 = QtWidgets.QLineEdit(self.frame)
        self.password_1.setGeometry(QtCore.QRect(40, 170, 351, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_1.sizePolicy().hasHeightForWidth())
        self.password_1.setSizePolicy(sizePolicy)
        self.password_1.setMinimumSize(QtCore.QSize(0, 0))
        self.password_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.password_1.setText("")
        self.password_1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_1.setClearButtonEnabled(True)
        self.password_1.setObjectName("password_1")
        self.password_2 = QtWidgets.QLineEdit(self.frame)
        self.password_2.setGeometry(QtCore.QRect(40, 250, 351, 51))
        self.password_2.setMinimumSize(QtCore.QSize(0, 0))
        self.password_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.password_2.setText("")
        self.password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_2.setClearButtonEnabled(True)
        self.password_2.setObjectName("password_2")
        self.btn_updatepassword = QtWidgets.QPushButton(self.frame)
        self.btn_updatepassword.setGeometry(QtCore.QRect(90, 330, 250, 51))
        self.btn_updatepassword.setMinimumSize(QtCore.QSize(250, 45))
        self.btn_updatepassword.setMaximumSize(QtCore.QSize(400, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_updatepassword.setFont(font)
        self.btn_updatepassword.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_updatepassword.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_updatepassword.setStyleSheet("QPushButton{\n"
"    background:rgb(83, 152, 255);\n"
"    border-radius:10px;\n"
"    color:#fff;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:none;\n"
"    background:rgb(68, 117, 222)\n"
"}\n"
"")
        self.btn_updatepassword.setObjectName("btn_updatepassword")
        self.frame_3 = QtWidgets.QFrame(UpdatePassword)
        self.frame_3.setGeometry(QtCore.QRect(-1, -1, 451, 501))
        self.frame_3.setStyleSheet("QFrame{\n"
"    background-image: url(:/images/img/login_2.jpg);\n"
"    border-top-left-radius:0px;\n"
"    border-top-right-radius:0px;\n"
"    border-bottom-left-radius:25px;\n"
"    border-bottom-right-radius:25px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_2 = QtWidgets.QFrame(UpdatePassword)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 451, 41))
        self.frame_2.setStyleSheet("QFrame{\n"
"background:rgba(0,0,0,0.60);\n"
"}\n"
"QFrame{\n"
"\n"
"border-radius:none;\n"
"\n"
"}\n"
"\n"
"QFrame:hover{\n"
"background:rgba(0,0,0,0.75);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btn_close = QtWidgets.QPushButton(self.frame_2)
        self.btn_close.setGeometry(QtCore.QRect(410, 0, 40, 38))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_close.setFont(font)
        self.btn_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_close.setStyleSheet("QPushButton{\n"
"background:rgba(0, 0, 0,0.15);\n"
"color:silver;\n"
"\n"
"border-radius:none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background:red;\n"
"color:white\n"
"}")
        self.btn_close.setObjectName("btn_close")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"color:silver;\n"
"background:transparent;")
        self.label_2.setObjectName("label_2")
        self.frame_3.raise_()
        self.frame.raise_()
        self.frame_2.raise_()

        self.retranslateUi(UpdatePassword)
        QtCore.QMetaObject.connectSlotsByName(UpdatePassword)

    def retranslateUi(self, UpdatePassword):
        _translate = QtCore.QCoreApplication.translate
        UpdatePassword.setWindowTitle(_translate("UpdatePassword", "Parol"))
        self.baslik_2.setText(_translate("UpdatePassword", "Parol almashtirish"))
        self.old_password.setPlaceholderText(_translate("UpdatePassword", "Eski parol"))
        self.password_1.setPlaceholderText(_translate("UpdatePassword", "Yangi parol"))
        self.password_2.setPlaceholderText(_translate("UpdatePassword", "Yangi parol qayta"))
        self.btn_updatepassword.setText(_translate("UpdatePassword", "Parolni o\'zgartirish"))
        self.btn_updatepassword.setShortcut(_translate("UpdatePassword", "Return"))
        self.btn_close.setText(_translate("UpdatePassword", "✕"))
        self.label_2.setText(_translate("UpdatePassword", "Parol"))
import images_rc
